name: X-Bot Daily Post

on:
  schedule:
    # Run at 9 AM UTC every day
    - cron: '0 9 * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  post-year-progress:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/x-bot/requirements.txt
          
      - name: Run X-Bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          cd apps/x-bot
          python bot.py
